export const ADD_NEW_BILL = "ADD_NEW_BILL";
export const ADD_NEW_CUSTOMER = "ADD_NEW_CUSTOMER";
export const LOAD_CONFIG_DATA = "LOAD_CONFIG_DATA";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const SETTLE_BILL = "SETTLE_BILL";
export const SETTLE_CUSTOMER = "SETTLE_CUSTOMER";
