module.exports = Object.freeze({
  BACKGROUND_COLOR: "#101820FF",
  PRIMARY_COLOUR: "#D4B996FF",
  SECONDARY_COLOUR: "#F2AA4CFF",
  SECONDARY_TEXT_COLOUR: "#101820FF",
  PRIMARY_ACTIVE_COLOR: "#F2AA4CFF",
  SECONDARY_ACTIVE_COLOR: "#F2AA4CFF",
  WHITE: "#FFF",
  SUCCESS: "#F2AA4CFF",
});
